### ISSUE TITLE
NPC icons overlap Key areas on map.

### ISSUE THREAD

**Issue by ArmoredArtist** [Volte6/GoMud#120]
![image](https://github.com/user-attachments/assets/7b1771b6-852b-48d3-8fd0-2528a931b59a)

NPC will overlap key areas like the bank in this screen shot (one north of me should be the bank). It should show the location before showing the NPC since the location is more important. (Unless you know of a way to show both)

**Comment by Volte6** [comment]
If you arr using the admin account your mapping skill is above the maximum (5 / 4). Those icons don't show for normal users. 

Try 'skillset map 4' to reduce it to normal

**Comment by Volte6** [comment]
Closing issue as non-bug
