### ISSUE TITLE
Add "lives" config value

### ISSUE THREAD

**Issue by Volte6** [Volte6/GoMud#38]
# Description

Introduce a new config "CharacterLives"
The goal is to allow a MUD server to configure whether and how many lives players are limited to before a character reset.

# Considerations 
* numeric value
  * -1 = unlimited
  * 0 = permadeath mode
  * 1+ = life count
* Should lives replenish? Based on in game play time, gaining levels, or other criteria/mechanics?
* What happens on a full death? Back to the void for race selection?

**Comment by ArmoredArtist** [comment]
I suggest lives should cost money somehow as a way to drain gold from the server. In many games, inflation becomes a problem over time, so it's important to find every possible way to encourage players to spend their gold. Lives should be the most expensive thing players can buy, as they represent the ultimate loss—everything your character owns and the character itself. This could serve as the ultimate gold sink. You could make the lives item dependent (that you must buy from a local alchemist), such as having a "phoenix crystal" on you at the time of death will allow you to revive and make those crystals cost an arm and a leg.

**Comment by ArmoredArtist** [comment]
Full death could have options able to be set by the server admin. All the way from "Back to the void for race selection and start from scratch" to starting new with a % of your previous experience/skills. An innovative way to multiclass could also be achieved from this. Perhaps the only way to multiclass could be if you make a class then die and reroll retaining a small percentage of the unique skills from the class you died with being added to the new character you roll who normally could not get these skills. This would encourage being as high a level as possible before dying to respec as the percentage it transfers over would be greater.

**Comment by Volte6** [comment]
Yeah, I like all these ideas. It's a great money sink if enabled, and there's no reason it can't be a script function as well.

**Comment by Volte6** [comment]
Coming soon:

<img width="796" alt="image" src="https://github.com/user-attachments/assets/245ce37f-1f4a-439e-9b66-b2fbd420fc0f">

**Comment by Volte6** [comment]
This has been added in this PR: https://github.com/Volte6/GoMud/pull/102

You only gain lives by leveling currently... when a place is figured out for buying it'll be added.

Closing.
