### ISSUE TITLE
Mudlet not recognizing characters

### ISSUE THREAD

**Issue by ArmoredArtist** [Volte6/GoMud#79]
This is one of the more popular mud clients so it should probably be fixed if you can.
![image](https://github.com/user-attachments/assets/58e2e684-c858-4b65-9588-442b1cd2f1f7)
![image3](https://github.com/user-attachments/assets/7ff8cc0c-500a-40fc-9b2d-540c47c330fa)
![image2](https://github.com/user-attachments/assets/f29d02d9-7982-4256-9e1c-06c453fdda2c)

**Comment by windu-ant** [comment]
Have you made sure to set the encoding type to utf-8? This should be in the general setting of Mudlet

**Comment by ArmoredArtist** [comment]
That solved it!

**Comment by Volte6** [comment]
Closing as non-issue.
