### ISSUE TITLE
Password masking continues into tutorial for all typing. 

### ISSUE THREAD

**Issue by ArmoredArtist** [Volte6/GoMud#82]
When I made a character earlier it masked my password but for the entire tutorial it was masking everything I typed after that. That should only be for the password. I was on the web client.

**Comment by Volte6** [comment]
This is the webclient I assume? I caught this while testing the "can't attack the dummy" bug and fixed it here: https://github.com/Volte6/GoMud/pull/76

**Comment by ArmoredArtist** [comment]
Your quicker than my bug reports! Yes sir, I did say the web client  :) :)

**Comment by Volte6** [comment]
Closing as completed.
